# Generated by Django 4.2.7 on 2024-09-22 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Комплектующие', 'verbose_name_plural': 'Комплектующии'},
        ),
        migrations.AlterField(
            model_name='production',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 18, 1, 1, 26677, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
