# Generated by Django 4.2.7 on 2024-09-22 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vehicle_options_alter_production_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 18, 2, 17, 225496, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
