# Generated by Django 4.2.7 on 2024-10-07 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_production_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 19, 59, 15, 612669, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
